name: Pipeline Dau Tien Cua Toi

on:
  push:
    branches:
      - main

jobs:
  say-hello-job:
    runs-on: ubuntu-latest
    
    steps:
      # Bước 1: Gọi công cụ đóng gói sẵn của GitHub để tải code về
      - name: Buoc 1 - Tai code ve may chu (Checkout)
        uses: actions/checkout@v4
      
      # Bước 2: Dùng lệnh Linux quen thuộc để kiểm tra xem code đã về chưa
      - name: Buoc 2 - Liet ke cac file dang co trong may chu
        run: ls -la
      
      - name: Buoc 3 - Gui loi chao
        run: echo "Code da duoc tai ve thanh cong!"
