name: Luong Kiem Thu Tu Dong (CI)

on:
  push:
    branches:
      - main

jobs:
  kiem-thu-he-thong:
    runs-on: ubuntu-latest
    
    steps:
      - name: Buoc 1 - Tai code ve may chu
        uses: actions/checkout@v4
      
      # Bước mới: Cài đặt Python tự động
      - name: Buoc 2 - Cai dat moi truong Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Chỉ định rõ phiên bản Python muốn dùng
      
      # Bước mới: Chạy file script
      - name: Buoc 3 - Chay kich ban kiem thu (Test)
        run: python check_system.py
